CREATE DATABASE IF NOT EXISTS PROJECTDATABASE
USE PROJECTDATABASE;
CREATE TABLE COMANDOS(
  	ID INT NOT NULL AUTO_INCREMENT
  	,TITULO VARCHAR(250) NULL
  	,COMANDO TEXT NULL
  	,EXECUTAPRINT BIT NULL
  	PRIMARY KEY (ID)
)
GO

CREATE TABLE BKP_COMANDOS(
	ID INT NULL
  	,NOME VARCHAR(250) NULL
  	,COMANDO TEXT NULL
  	,EXECUTAPRINT BIT NULL
	,DATAATUALIZACAO DATETIME NOT NULL)

CREATE TRIGGER BACKUPCOMANDOS  
ON COMANDOS 
AFTER UPDATE,DELETE AS
begin
	INSERT INTO BKP_COMANDOS(ID  
  	,NOME
  	,COMANDO 
  	,EXECUTAPRINT 
	,CAMINHOPRINT) 
     SELECT ID  
  	,NOME
  	,COMANDO 
  	,EXECUTAPRINT
	,GETDATE() FROM DELETED
GO  

CREATE PROCEDURE SP_EXCLUIRREGISTROSANTIGOS
AS
    DECLARE @DATALIMITE DATETIME;
    SET @DATALIMITE = DATEADD(MONTH, -1, GETDATE());
	
    DELETE FROM BKP_COMANDOS
    WHERE DATAATUALIZACAO < @DATALIMITE;
GO











    